networks:
  application-network:
    name: application-network
  monitoring-network:
    name: monitoring-network

volumes:
  backend-db:


services:
  backend:
    image: ghcr.io/czarsimon/bolesta-booking/backend:2.0.0
    volumes:
      - backend-db:/var/bolesta-booking
    environment:
      - DB_FILENAME=/var/bolesta-booking/db.sql
      - ENABLE_CREATE_USERS=true
    networks:
      - application-network
      - monitoring-network
    ports:
      - "8080:8080"

  httplogger:
    image: czarsimon/httplogger:1.0.0
    environment:
      JAEGER_DISABLED: "true"
    networks:
      - monitoring-network
