networks:
  application-network:
    name: application-network
  monitoring-network:
    name: monitoring-network

services:
  backend:
    image: ghcr.io/czarsimon/bolesta-booking/backend:1.0.0
    networks:
      - application-network

  httplogger:
    image: czarsimon/httplogger:0.8
    environment:
      JAEGER_DISABLED: "true"
    networks:
      - monitoring-network