name: backend-pipeline

defaults:
  run:
    working-directory: backend

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-pipeline.yml

jobs:
  parse-version:
    name: parse-version
    runs-on: ubuntu-latest
    outputs:
      full-version: ${{ steps.parse.outputs.full-version }}
    steps:
      - uses: actions/checkout@v2
      - id: parse
        name: Parse version info
        run: |
          VERSION=$(cat package.json | jq .version --raw-output)
          COMMIT_ID=${GITHUB_SHA:0:7}
          echo "::set-output name=full-version::$VERSION-$COMMIT_ID"
  
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - run: npm ci

  security-scans:
    name: security-scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan dependencies
        run: npm audit --omit=dev
      - name: Scan configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          format: "table"
          exit-code: "1"
          scan-ref: "backend"
          hide-progress: false
          ignore-unfixed: true

  build-image:
    name: build-image
    if: github.ref == 'refs/heads/main'
    needs:
      - parse-version
      - security-scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Docker build
        run: |
          echo "Package version: ${{needs.parse-version.outputs.package-name}}"
          docker build -t ghcr.io/czarsimon/bolesta-booking/backend/${{needs.parse-version.outputs.full-version}} .
      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "ghcr.io/czarsimon/bolesta-booking/backend/${{needs.parse-version.outputs.full-version}}"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"