name: backend-pipeline

defaults:
  run:
    working-directory: backend

on:
  push:
    paths:
      - backend/**
      - .github/workflows/backend-pipeline.yml

jobs:
  parse-version:
    name: parse-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: parse
        name: Parse version info
        run: |
          VERSION=$(cat package.json | jq .version --raw-output)
          echo "::set-output name=version::$VERSION"

  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: go mod download
      - name: Check code style
        run: go vet ./...
      - name: Test
        run: go test ./...

  security-scans:
    name: security-scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan code
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.14.0
          $(go env GOPATH)/bin/gosec ./...
      - name: Scan configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          format: "table"
          exit-code: "1"
          scan-ref: "backend"
          hide-progress: false
          ignore-unfixed: true
        env:
          TRIVY_IGNOREFILE: "backend/.trivyignore"

  build-image:
    name: build-image
    if: github.ref == 'refs/heads/main'
    needs:
      - parse-version
      - run-tests
      - security-scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Docker build
        run: |
          echo "Package version: ${{needs.parse-version.outputs.package-name}}"
          docker build \
            -t ghcr.io/czarsimon/bolesta-booking/backend:${{needs.parse-version.outputs.version}} \
            --label git-commit="$(git rev-parse HEAD)" \
            --label build-date="$(date -u)" \
            --label commiter-name="$(git show -s --format='%an')" \
            --label commiter-email="$(git show -s --format='%ae')" \
            .
      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "ghcr.io/czarsimon/bolesta-booking/backend:${{needs.parse-version.outputs.version}}"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"
      - name: Docker push
        run: |
          docker login https://ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/czarsimon/bolesta-booking/backend:${{needs.parse-version.outputs.version}}
