name: deployment-pipeline

defaults:
  run:
    working-directory: infrastructure

on:
  push:
    paths:
      - infrastructure/docker-compose.yml
      - infrastructure/nginx.conf
      - fronend
      - .github/workflows/deployment-pipeline.yml

env:
  SERVER_HOST: booking.xn--blesta-wxa.se

jobs:
  security-scan:
    name: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      - name: scan deployment images
        run: |
          for IMAGE in $(cat docker-compose.yml | grep 'image: ' | awk '{print $NF}'); do echo $IMAGE; trivy image --ignore-unfixed --exit-code 1 $IMAGE; done;

  build-and-upload-frontend:
    name: build-and-upload-frontend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - security-scan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: install dependencies
        run: npm ci
        working-directory: frontend
      - name: build application
        env:
          REACT_APP_BASE_URL: "/api"
        run: npm run build
        working-directory: frontend
      - name: upload built application
        working-directory: frontend
        env:
          AWS_REGION: "fr-par"
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_FE_UPLOAD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_FE_UPLOAD_SECRET_KEY }}
        run: |
          aws s3 sync \
            ./build \
            s3://bolesta-booking-frontend \
            --endpoint-url https://s3.fr-par.scw.cloud \
            --acl public-read

  rsync-deployment-files:
    name: rsync-deployment-files
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - security-scan
    steps:
      - uses: actions/checkout@v2
      - name: upload env creation file
        uses: burnett01/rsync-deployments@5.2.1
        with:
          path: "./infrastructure/create-env-file.sh"
          remote_path: /home/cicd
          remote_host: ${{ env.SERVER_HOST }}
          remote_user: cicd
          remote_key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
      - name: upload compose file
        uses: burnett01/rsync-deployments@5.2.1
        with:
          path: "./infrastructure/docker-compose.yml"
          remote_path: /home/cicd
          remote_host: ${{ env.SERVER_HOST }}
          remote_user: cicd
          remote_key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
      - name: upload nginx config
        uses: burnett01/rsync-deployments@5.2.1
        with:
          path: "./infrastructure/nginx.conf"
          remote_path: /home/cicd
          remote_host: ${{ env.SERVER_HOST }}
          remote_user: cicd
          remote_key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}

  reload-nginx:
    name: reload-nginx
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - rsync-deployment-files
      - build-and-upload-frontend
    steps:
      - name: copying nginx config to correct folder and reloading
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: cicd
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |
            cp /etc/nginx/sites-available/default nginx.conf.backup
            sudo cp nginx.conf /etc/nginx/sites-available/default  
            sudo nginx -t
            sudo systemctl reload nginx

  start-containers:
    name: start-containers
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - rsync-deployment-files
      - build-and-upload-frontend
    steps:
      - name: create env and start containers
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: cicd
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          script: |
            chmod 700 create-env-file.sh
            LITESTREAM_ACCESS_KEY_ID=${{ secrets.SCW_FE_UPLOAD_ACCESS_KEY }} \
              LITESTREAM_ACCESS_KEY_SECRET=${{ secrets.SCW_FE_UPLOAD_SECRET_KEY }} \
              ./create-env-file.sh
            chmod 400 .env
            docker-compose pull
            docker-compose --env-file=.env up -d
