name: backend-pipeline

defaults:
  run:
    working-directory: infrastructure/dockmon

on:
  push:
    paths:
      - infrastructure/dockmon/**
      - .github/workflows/dockmon-pipeline.yml

jobs:
  parse-version:
    name: parse-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: parse
        name: Parse version info
        run: |
          VERSION=$(cat package.json | jq .version --raw-output)
          echo "::set-output name=version::$VERSION"

  security-scans:
    name: security-scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          format: "table"
          exit-code: "1"
          scan-ref: "infrastructure/dockmon"
          hide-progress: false
          ignore-unfixed: true
        env:
          TRIVY_IGNOREFILE: "infrastructure/dockmon/.trivyignore"

  build-image:
    name: build-image
    if: github.ref == 'refs/heads/main'
    needs:
      - security-scans
      - parse-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Docker build
        run: |
          echo "Package version: ${{needs.parse-version.outputs.package-name}}"
          docker build \
            -t ghcr.io/czarsimon/bolesta-booking/dockmon:${{needs.parse-version.outputs.version}} \
            --label git-commit="$(git rev-parse HEAD)" \
            --label build-date="$(date -u)" \
            --label commiter-name="$(git show -s --format='%an')" \
            --label commiter-email="$(git show -s --format='%ae')" \
            .
      - name: Run Trivy vulnerability scanner on image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "ghcr.io/czarsimon/bolesta-booking/dockmon:${{needs.parse-version.outputs.version}}"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"
      - name: Docker push
        run: |
          docker login https://ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/czarsimon/bolesta-booking/dockmon:${{needs.parse-version.outputs.version}}
