name: terraform-pipeline

defaults:
  run:
    working-directory: infrastructure/terraform

on:
  push:
    paths:
      - infrastructure/terraform/**
      - .github/workflows/terraform-pipeline.yml

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
  AWS_DEFAULT_REGION: fr-par

jobs:
  scan-and-test:
    name: scan-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan configuration
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          format: "table"
          exit-code: "1"
          scan-ref: "infrastructure/terraform"
          hide-progress: false
          ignore-unfixed: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: init terraform
        run: terraform init
      - name: fmt check
        run: terraform fmt -check
      - name: validation
        run: terraform validate -no-color

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - scan-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform apply -auto-approve

